name: SimpleWarps
main: me.NerdsWBNerds.SimpleWarps.SimpleWarps
version: 1.2
commands:
   warp:
      description: Show list of warp, or warp to or warp other people to a warp.
      usage: /warp or /warp <warp_name> or /warp <player_name> <warp_name>
   setwarp:
      description: Set a warp at your location
      usage: /setwarp <name>
   addwarp:
      description: Set a warp at your location
      usage: /addwarp <name>
   delwarp:
      description: Delete warp
      usage: /delwarp <name>
   removewarp:
      description: Delete warp
      usage: /removewarp <name>